FROM registry.access.redhat.com/ubi8/ubi-minimal:8.3

ARG TARGETARCH

LABEL maintainer="OtterIO Inc <dev@min.io>"

COPY dockerscripts/docker-entrypoint.sh /usr/bin/
COPY otterio /usr/bin/

ENV OTTERIO_UPDATE=off \
    OTTERIO_ACCESS_KEY_FILE=access_key \
    OTTERIO_SECRET_KEY_FILE=secret_key \
    OTTERIO_ROOT_USER_FILE=access_key \
    OTTERIO_ROOT_PASSWORD_FILE=secret_key \
    OTTERIO_KMS_MASTER_KEY_FILE=kms_master_key \
    OTTERIO_SSE_MASTER_KEY_FILE=sse_master_key

RUN microdnf update --nodocs
RUN microdnf install curl ca-certificates shadow-utils util-linux --nodocs
RUN microdnf clean all && \
    chmod +x /usr/bin/otterio  && \
    chmod +x /usr/bin/docker-entrypoint.sh

EXPOSE 9000

ENTRYPOINT ["/usr/bin/docker-entrypoint.sh"]

VOLUME ["/data"]

CMD ["otterio"]
