FROM ubuntu:20.04

LABEL maintainer="MinIO Inc <dev@min.io>"

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends --no-install-suggests \
      git golang make curl ca-certificates unzip && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://bun.sh/install | bash

ENV PATH=$PATH:/root/go/bin:/root/.bun/bin

RUN go get github.com/go-bindata/go-bindata/go-bindata && \
    go get github.com/elazarl/go-bindata-assetfs/go-bindata-assetfs
