version: '3.7'

services:
  otterio1:
    image: minio/minio:latest
    hostname: otterio1
    volumes:
      - otterio1-data:/export
    ports:
      - "9001:9000"
    networks:
      - otterio_distributed
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.otterio1==true
    command: server http://otterio{1...4}/export
    secrets:
      - secret_key
      - access_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/otterio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  otterio2:
    image: minio/minio:latest
    hostname: otterio2
    volumes:
      - otterio2-data:/export
    ports:
      - "9002:9000"
    networks:
      - otterio_distributed
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.otterio2==true
    command: server http://otterio{1...4}/export
    secrets:
      - secret_key
      - access_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/otterio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  otterio3:
    image: minio/minio:latest
    hostname: otterio3
    volumes:
      - otterio3-data:/export
    ports:
      - "9003:9000"
    networks:
      - otterio_distributed
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.otterio3==true
    command: server http://otterio{1...4}/export
    secrets:
      - secret_key
      - access_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/otterio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  otterio4:
    image: minio/minio:latest
    hostname: otterio4
    volumes:
      - otterio4-data:/export
    ports:
      - "9004:9000"
    networks:
      - otterio_distributed
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.otterio4==true
    command: server http://otterio{1...4}/export
    secrets:
      - secret_key
      - access_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/otterio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  otterio1-data:

  otterio2-data:

  otterio3-data:

  otterio4-data:

networks:
  otterio_distributed:
    driver: overlay

secrets:
  secret_key:
    external: true
  access_key:
    external: true
